# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/eugene/university/2 course/c++/hw/Tic-tac-toe"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/eugene/university/2 course/c++/hw/Tic-tac-toe"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/eugene/university/2 course/c++/hw/Tic-tac-toe/CMakeFiles" "/home/eugene/university/2 course/c++/hw/Tic-tac-toe/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/eugene/university/2 course/c++/hw/Tic-tac-toe/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tic_Tac_Toe

# Build rule for target.
Tic_Tac_Toe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tic_Tac_Toe
.PHONY : Tic_Tac_Toe

# fast build rule for target.
Tic_Tac_Toe/fast:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/build
.PHONY : Tic_Tac_Toe/fast

#=============================================================================
# Target rules for targets named build-time-make-directory

# Build rule for target.
build-time-make-directory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build-time-make-directory
.PHONY : build-time-make-directory

# fast build rule for target.
build-time-make-directory/fast:
	$(MAKE) -f CMakeFiles/build-time-make-directory.dir/build.make CMakeFiles/build-time-make-directory.dir/build
.PHONY : build-time-make-directory/fast

src/EpollLoop.o: src/EpollLoop.cpp.o
.PHONY : src/EpollLoop.o

# target to build an object file
src/EpollLoop.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/EpollLoop.cpp.o
.PHONY : src/EpollLoop.cpp.o

src/EpollLoop.i: src/EpollLoop.cpp.i
.PHONY : src/EpollLoop.i

# target to preprocess a source file
src/EpollLoop.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/EpollLoop.cpp.i
.PHONY : src/EpollLoop.cpp.i

src/EpollLoop.s: src/EpollLoop.cpp.s
.PHONY : src/EpollLoop.s

# target to generate assembly for a file
src/EpollLoop.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/EpollLoop.cpp.s
.PHONY : src/EpollLoop.cpp.s

src/GameServer.o: src/GameServer.cpp.o
.PHONY : src/GameServer.o

# target to build an object file
src/GameServer.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/GameServer.cpp.o
.PHONY : src/GameServer.cpp.o

src/GameServer.i: src/GameServer.cpp.i
.PHONY : src/GameServer.i

# target to preprocess a source file
src/GameServer.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/GameServer.cpp.i
.PHONY : src/GameServer.cpp.i

src/GameServer.s: src/GameServer.cpp.s
.PHONY : src/GameServer.s

# target to generate assembly for a file
src/GameServer.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/GameServer.cpp.s
.PHONY : src/GameServer.cpp.s

src/HttpClient.o: src/HttpClient.cpp.o
.PHONY : src/HttpClient.o

# target to build an object file
src/HttpClient.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpClient.cpp.o
.PHONY : src/HttpClient.cpp.o

src/HttpClient.i: src/HttpClient.cpp.i
.PHONY : src/HttpClient.i

# target to preprocess a source file
src/HttpClient.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpClient.cpp.i
.PHONY : src/HttpClient.cpp.i

src/HttpClient.s: src/HttpClient.cpp.s
.PHONY : src/HttpClient.s

# target to generate assembly for a file
src/HttpClient.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpClient.cpp.s
.PHONY : src/HttpClient.cpp.s

src/HttpRequest.o: src/HttpRequest.cpp.o
.PHONY : src/HttpRequest.o

# target to build an object file
src/HttpRequest.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpRequest.cpp.o
.PHONY : src/HttpRequest.cpp.o

src/HttpRequest.i: src/HttpRequest.cpp.i
.PHONY : src/HttpRequest.i

# target to preprocess a source file
src/HttpRequest.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpRequest.cpp.i
.PHONY : src/HttpRequest.cpp.i

src/HttpRequest.s: src/HttpRequest.cpp.s
.PHONY : src/HttpRequest.s

# target to generate assembly for a file
src/HttpRequest.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpRequest.cpp.s
.PHONY : src/HttpRequest.cpp.s

src/HttpResponse.o: src/HttpResponse.cpp.o
.PHONY : src/HttpResponse.o

# target to build an object file
src/HttpResponse.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpResponse.cpp.o
.PHONY : src/HttpResponse.cpp.o

src/HttpResponse.i: src/HttpResponse.cpp.i
.PHONY : src/HttpResponse.i

# target to preprocess a source file
src/HttpResponse.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpResponse.cpp.i
.PHONY : src/HttpResponse.cpp.i

src/HttpResponse.s: src/HttpResponse.cpp.s
.PHONY : src/HttpResponse.s

# target to generate assembly for a file
src/HttpResponse.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpResponse.cpp.s
.PHONY : src/HttpResponse.cpp.s

src/HttpServer.o: src/HttpServer.cpp.o
.PHONY : src/HttpServer.o

# target to build an object file
src/HttpServer.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpServer.cpp.o
.PHONY : src/HttpServer.cpp.o

src/HttpServer.i: src/HttpServer.cpp.i
.PHONY : src/HttpServer.i

# target to preprocess a source file
src/HttpServer.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpServer.cpp.i
.PHONY : src/HttpServer.cpp.i

src/HttpServer.s: src/HttpServer.cpp.s
.PHONY : src/HttpServer.s

# target to generate assembly for a file
src/HttpServer.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/HttpServer.cpp.s
.PHONY : src/HttpServer.cpp.s

src/TcpClient.o: src/TcpClient.cpp.o
.PHONY : src/TcpClient.o

# target to build an object file
src/TcpClient.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/TcpClient.cpp.o
.PHONY : src/TcpClient.cpp.o

src/TcpClient.i: src/TcpClient.cpp.i
.PHONY : src/TcpClient.i

# target to preprocess a source file
src/TcpClient.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/TcpClient.cpp.i
.PHONY : src/TcpClient.cpp.i

src/TcpClient.s: src/TcpClient.cpp.s
.PHONY : src/TcpClient.s

# target to generate assembly for a file
src/TcpClient.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/TcpClient.cpp.s
.PHONY : src/TcpClient.cpp.s

src/TcpServer.o: src/TcpServer.cpp.o
.PHONY : src/TcpServer.o

# target to build an object file
src/TcpServer.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/TcpServer.cpp.o
.PHONY : src/TcpServer.cpp.o

src/TcpServer.i: src/TcpServer.cpp.i
.PHONY : src/TcpServer.i

# target to preprocess a source file
src/TcpServer.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/TcpServer.cpp.i
.PHONY : src/TcpServer.cpp.i

src/TcpServer.s: src/TcpServer.cpp.s
.PHONY : src/TcpServer.s

# target to generate assembly for a file
src/TcpServer.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/TcpServer.cpp.s
.PHONY : src/TcpServer.cpp.s

src/TcpSocket.o: src/TcpSocket.cpp.o
.PHONY : src/TcpSocket.o

# target to build an object file
src/TcpSocket.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/TcpSocket.cpp.o
.PHONY : src/TcpSocket.cpp.o

src/TcpSocket.i: src/TcpSocket.cpp.i
.PHONY : src/TcpSocket.i

# target to preprocess a source file
src/TcpSocket.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/TcpSocket.cpp.i
.PHONY : src/TcpSocket.cpp.i

src/TcpSocket.s: src/TcpSocket.cpp.s
.PHONY : src/TcpSocket.s

# target to generate assembly for a file
src/TcpSocket.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/TcpSocket.cpp.s
.PHONY : src/TcpSocket.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Tic_Tac_Toe.dir/build.make CMakeFiles/Tic_Tac_Toe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Tic_Tac_Toe"
	@echo "... build-time-make-directory"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/EpollLoop.o"
	@echo "... src/EpollLoop.i"
	@echo "... src/EpollLoop.s"
	@echo "... src/GameServer.o"
	@echo "... src/GameServer.i"
	@echo "... src/GameServer.s"
	@echo "... src/HttpClient.o"
	@echo "... src/HttpClient.i"
	@echo "... src/HttpClient.s"
	@echo "... src/HttpRequest.o"
	@echo "... src/HttpRequest.i"
	@echo "... src/HttpRequest.s"
	@echo "... src/HttpResponse.o"
	@echo "... src/HttpResponse.i"
	@echo "... src/HttpResponse.s"
	@echo "... src/HttpServer.o"
	@echo "... src/HttpServer.i"
	@echo "... src/HttpServer.s"
	@echo "... src/TcpClient.o"
	@echo "... src/TcpClient.i"
	@echo "... src/TcpClient.s"
	@echo "... src/TcpServer.o"
	@echo "... src/TcpServer.i"
	@echo "... src/TcpServer.s"
	@echo "... src/TcpSocket.o"
	@echo "... src/TcpSocket.i"
	@echo "... src/TcpSocket.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

